apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJuZXh1cy5kZXYuc2NyYXBlaGVyby5jb20iOnsidXNlcm5hbWUiOiJsYWJlZWJ1ZGVlbiIsInBhc3N3b3JkIjoiamxrZGpmZHMiLCJhdXRoIjoiYkdGaVpXVmlkV1JsWlc0NmFteHJaR3BtWkhNPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2021-07-22T05:04:37Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:.dockerconfigjson: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2021-07-22T05:04:37Z"
  name: regcred
  namespace: default
  resourceVersion: "1432"
  selfLink: /api/v1/namespaces/default/secrets/regcred
  uid: f03b87b5-ebd6-4980-a8fe-28d83fa48615
type: kubernetes.io/dockerconfigjson
